"use client";
import { useEffect, useState } from "react";
import type { AstroTarotLayer } from "@/lib/astrology-types";
import { englishCardCopy } from "@/lib/reading-en";

type Card={id:string;name:string;keywords:string[]};
type Reading={cardReadings:Array<{cardId:string;cardName:string;position:string;positionDescription:string;text:string}>;connections:string;summary:string;reflection:string;disclaimer:string};
type Order={id:number;orderNumber:string;customerName:string;category:string;question:string;paymentStatus:string;readingStatus:string;cards:Card[]|null;reading:Reading|null;astrology?:AstroTarotLayer|null;astrologyStatus?:string|null};

const CATEGORY_EN:Record<string,string>={"Amor e relacionamentos":"Love & attraction","Dinheiro":"Money & growth","Trabalho e carreira":"Career & ambition","Decisões":"Decision & direction"};

export default function ReadingEnClient({token}:{token:string}){
  const [order,setOrder]=useState<Order|null>(null); const [error,setError]=useState("");
  const [birthDate,setBirthDate]=useState(""); const [birthTime,setBirthTime]=useState(""); const [birthPlace,setBirthPlace]=useState(""); const [timeKnown,setTimeKnown]=useState(true);
  const [astroLoading,setAstroLoading]=useState(false); const [astroError,setAstroError]=useState(""); const [interest,setInterest]=useState("");
  useEffect(()=>{let active=true;const load=async()=>{try{const r=await fetch(`/api/orders/${token}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Reading not found.");if(active)setOrder(d);}catch(e){if(active)setError(e instanceof Error?e.message:"Unable to load your reading.");}};void load();const timer=setInterval(load,5000);return()=>{active=false;clearInterval(timer)};},[token]);
  async function submitAstrology(e:React.FormEvent){e.preventDefault();setAstroError("");setAstroLoading(true);try{
    const response=await fetch(`/api/orders/${token}/astrology`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({birthDate,birthTime,birthPlace,timeKnown})});
    const data=await response.json(); if(!response.ok) throw new Error(data.error||"We could not calculate your chart right now.");
    setOrder(current=>current?{...current,astrology:data.astrology,astrologyStatus:"generated"}:current);
  }catch(err){setAstroError(err instanceof Error?err.message:"We could not calculate your chart right now.");}finally{setAstroLoading(false);}}

  function track(event:string, metadata:Record<string,unknown>={}){void fetch("/api/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event,orderId:order?.id,anonymous_id:`reading:${token}`,session_id:`reading:${token}`,metadata:{locale:"en-US",currency:"USD",market:"international",...metadata}})});}
  function showInterest(product:string,price:number){setInterest(product);track("upsell_interest",{product,price});}

  if(error)return <main className="en-status-page"><div className="en-status-orb">✦</div><h1>We could not open this reading</h1><p>{error}</p><a className="en-cta" href="/en">RETURN TO CHAMA SOFIA</a></main>;
  if(!order)return <main className="en-status-page"><div className="en-status-orb">✦</div><h1>Preparing your private space...</h1></main>;
  const paid=["paid","reading_generated","delivered"].includes(order.paymentStatus)||["reading_generated","delivered"].includes(order.readingStatus);
  if(!paid)return <main className="en-status-page"><div className="en-status-orb">✦</div><h1>Your payment is still being confirmed.</h1><p>This page updates automatically. You do not need to pay twice.</p></main>;
  if(!order.reading||!order.cards)return <main className="en-status-page"><div className="en-status-orb">✦</div><h1>Your reading is being generated...</h1><p>Keep this private link open for a moment.</p></main>;
  if(!order.astrology)return <main className="en-reading-shell"><header className="en-reading-head"><a href="/en" className="en-brand"><img src="/assets/brand/chama-sofia-logo.png" alt=""/><span>CHAMA SOFIA</span></a><span>Order {order.orderNumber}</span></header><section className="en-birth-card"><p className="en-kicker">PAYMENT CONFIRMED · FINAL PERSONALIZATION</p><h1>Now let’s connect your birth sky to the cards.</h1><p>Enter your birth details. Your location is used to resolve coordinates and historical time zone for the chart.</p><form onSubmit={submitAstrology}><label>Date of birth<input required type="date" value={birthDate} onChange={e=>setBirthDate(e.target.value)}/></label><label>Birth time<input required={timeKnown} disabled={!timeKnown} type="time" value={birthTime} onChange={e=>setBirthTime(e.target.value)}/></label><label className="en-time-check"><input type="checkbox" checked={!timeKnown} onChange={e=>setTimeKnown(!e.target.checked)}/> I don’t know my birth time</label><label>City, state/province and country<input required value={birthPlace} onChange={e=>setBirthPlace(e.target.value)} placeholder="Example: Austin, Texas, USA"/></label>{astroError&&<p className="en-error">{astroError}</p>}<button className="en-cta" disabled={astroLoading}>{astroLoading?'CALCULATING YOUR SKY...':'GENERATE MY BIRTH CHART + TAROT'} <span>→</span></button><small>If your birth time is unknown, the reading remains useful, but Ascendant and houses are not treated as precise.</small></form></section></main>;

  return <main className="en-reading-shell"><header className="en-reading-head"><a href="/en" className="en-brand"><img src="/assets/brand/chama-sofia-logo.png" alt=""/><span>CHAMA SOFIA</span></a><span>Reading {order.orderNumber}</span></header><section className="en-reading-hero"><p className="en-kicker">YOUR PRIVATE ASTROLOGY + TAROT READING</p><h1>Hello, {order.customerName.split(" ")[0]}.</h1><p>Your sky and your three cards are ready to be read together.</p><blockquote>“{order.question}”</blockquote><small>{CATEGORY_EN[order.category]||order.category}</small></section>
  <section className="en-reading-cards">{order.cards.map((card,index)=>{const copy=englishCardCopy(card.id);const reading=order.reading!.cardReadings[index];return <article key={card.id}><img src={`/assets/tarot/cards/${card.id}.webp`} alt={copy?.name||reading.cardName}/><div><p className="en-kicker">{reading.position}</p><h2>{copy?.name||reading.cardName}</h2><p>{reading.text}</p><div className="en-keywords">{copy?.keywords.map(k=><span key={k}>{k}</span>)}</div></div></article>})}</section>
  <section className="en-reading-summary"><div><p className="en-kicker">HOW THE CARDS SPEAK TO EACH OTHER</p><h2>The pattern behind your three cards</h2><p>{order.reading.connections}</p></div><div className="en-summary-box"><p className="en-kicker">THE CORE MESSAGE</p><p>{order.reading.summary}</p></div><blockquote>{order.reading.reflection}</blockquote></section>
  <section className="en-astro-result"><p className="en-kicker">YOUR BIRTH SKY + CURRENT SKY</p><h2>What astrology adds to your question</h2><p>{order.astrology.situation}</p><div className="en-natal-grid">{[["Sun",order.astrology.natal.sun?.sign],["Moon",order.astrology.natal.moon?.sign],["Ascendant",order.astrology.natal.ascendantSign]].map(([label,value])=>value&&<article key={String(label)}><small>{label}</small><strong>{value}</strong></article>)}</div>{order.astrology.current.highlights.length>0&&<div className="en-transits"><h3>Current movements with the most weight</h3>{order.astrology.current.highlights.slice(0,3).map((item,index)=><article key={`${item.transitPlanet}-${index}`}><strong>{item.transitPlanet} · {item.aspectType}</strong><p>{item.meaning}</p></article>)}</div>}<div className="en-astro-bridge"><h3>Where your sky meets your cards</h3><p>{order.astrology.cardsBridge}</p></div><div className="en-solution"><p className="en-kicker">YOUR PRACTICAL DIRECTION</p><h3>{order.astrology.solution.title}</h3>{order.astrology.solution.steps.map(step=><article key={step.title}><strong>{step.title}</strong><p>{step.text}</p></article>)}</div><blockquote>{order.astrology.reflection}</blockquote><small>{order.astrology.precisionNote}</small><div className="en-pdf-box"><div><strong>Keep your complete reading</strong><span>Your personalized English PDF is included at no extra charge.</span></div><a href={`/api/pdf/${token}`} className="en-cta">DOWNLOAD MY PDF <span>↓</span></a></div></section>
  <section className="en-upsell"><p className="en-kicker">IF YOU WANT TO GO DEEPER</p><h2>Your first reading can be the beginning.</h2><p>We are testing the next experiences before releasing them. Your interest helps us decide what to build first.</p><div className="en-upsell-grid"><article><small>DEEP DIVE</small><h3>Expanded personal reading</h3><strong>$4.99</strong><p>A longer interpretation with more context, tensions and practical direction around this same question.</p><button onClick={()=>showInterest("deep-dive",4.99)}>{interest==="deep-dive"?"INTEREST SAVED ✓":"I WANT THIS NEXT"}</button></article><article><small>LOVE</small><h3>Compatibility reading</h3><strong>$7.99</strong><p>Your chart + another person’s birth data + Tarot focused on attraction, reciprocity and relationship dynamics.</p><button onClick={()=>showInterest("love-compatibility",7.99)}>{interest==="love-compatibility"?"INTEREST SAVED ✓":"I WANT THIS NEXT"}</button></article><article><small>ANOTHER QUESTION</small><h3>Start a fresh reading</h3><strong>$1.99</strong><p>Use a different question and reveal a new set of three cards.</p><a href="/en/consult" onClick={()=>track("new_reading_click",{product:"new-reading",price:1.99})}>START ANOTHER READING →</a></article></div></section>
  <section className="en-reading-end"><p>{order.reading.disclaimer}</p><a className="en-cta" href="/en/consult" onClick={()=>track("new_reading_click",{product:"new-reading",price:1.99})}>START A NEW READING <span>→</span></a></section></main>;
}
