'use client';
import { useCallback,useEffect,useState } from 'react';

type Order={id:number;order_number:string;public_token:string;customer_name:string;customer_email?:string;customer_whatsapp?:string;category:string;question:string;price:number;payment_status:string;reading_status:string;created_at:string;utm_source?:string;utm_campaign?:string;utm_content?:string;device_type?:string;is_test:number;landing_variant:string;offer_code:string;upsell_status:string;recovery_first_sent_at?:string;recovery_second_sent_at?:string;recovery_error?:string};
type Review={id:number;order_number:string;rating:number;comment?:string;display_name:string;public_consent:number;moderation_status:string;featured:number;is_test:number;created_at:string};
type Filters={period:string;source:string;campaign:string;creative:string;device:string;variant:string;offer:string};
type Data={orders:Order[];filters:{selected:Filters;options:{sources:string[];campaigns:string[];creatives:string[];devices:string[];variants:string[];offers:string[]}};dashboard:{visitors:number;sessions:number;totalSales:number;revenue:number;baseRevenue:number;essentialRevenue:number;completeRevenue:number;upsellRevenue:number;upsells:number;completeSales:number;completeAdoption:number;upsellRate:number;averageTicket:number;pending:number;generated:number;conversion:number;pricing:{formatted:string;remaining:number|null};test:{total:number;sales:number;revenue:number;pending:number};funnel:{visitors:number;sessions:number;cta:number;questions:number;offers:number;pix:number;paid:number};behavior:{depth25:number;depth50:number;depth75:number;depth90:number;faqOpened:number;contactClicks:number;pageHidden:number;questionStarted:number;lastActivity:number};abandonment:{beforeCta:number;afterCta:number;afterQuestion:number;afterOffer:number;afterPix:number};pricePerformance:{price:number;checkouts:number;sales:number;conversion:number}[];recovery:{openForms:number;formFirst:number;pixFirst:number;second:number;resumed:number};growth:{referrals:number;upsellClicks:number};economics:{dailySpend:number;estimatedSpend:number;cac:number|null;roas:number|null;revenuePerVisitor:number};guardian:{level:string;label:string;message:string}}};

const initialFilters:Filters={period:'30d',source:'all',campaign:'all',creative:'all',device:'all',variant:'all',offer:'all'};
const money=(c:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100);
const adVariants=[
  {id:'personalizada',label:'A · leitura personalizada',headline:'Sua pergunta. Três cartas. Uma leitura só sua.',primary:'Faça sua leitura personalizada de 3 cartas e receba também o e-book Tarot para Iniciantes.'},
  {id:'leitura-ebook',label:'B · leitura + e-book',headline:'Leitura personalizada + e-book completo por R$ 9,90',primary:'Receba 3 cartas, interpretação em PDF e o livro Tarot para Iniciantes em uma experiência digital completa.'},
  {id:'pdf',label:'C · PDF e bônus',headline:'Revele suas cartas e guarde sua leitura em PDF',primary:'Faça sua pergunta, receba a interpretação personalizada e baixe seu PDF e e-book após o Pix.'},
];

export default function AdminClient(){
  const [data,setData]=useState<Data|null>(null),[reviews,setReviews]=useState<Review[]>([]),[login,setLogin]=useState(true),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(''),[bookStatus,setBookStatus]=useState(''),[filters,setFilters]=useState<Filters>(initialFilters),[dailySpend,setDailySpend]=useState('10,00'),[completePrice,setCompletePrice]=useState('19,90'),[upsellPrice,setUpsellPrice]=useState('9,90');
  const load=useCallback(async(current=filters)=>{
    const query=new URLSearchParams(current).toString();const [ordersResponse,reviewsResponse,offersResponse]=await Promise.all([fetch(`/api/admin/orders?${query}`,{cache:'no-store'}),fetch('/api/admin/reviews',{cache:'no-store'}),fetch('/api/offers',{cache:'no-store'})]);
    if(ordersResponse.status===401){setLogin(true);return;}const result=await ordersResponse.json() as Data;setData(result);setDailySpend((result.dashboard.economics.dailySpend/100).toFixed(2).replace('.',','));setLogin(false);
    if(reviewsResponse.ok){const reviewData=await reviewsResponse.json() as {reviews:Review[]};setReviews(reviewData.reviews||[]);}
    if(offersResponse.ok){const offerData=await offersResponse.json() as {complete:{cents:number};upsell:{cents:number}};setCompletePrice((offerData.complete.cents/100).toFixed(2).replace('.',','));setUpsellPrice((offerData.upsell.cents/100).toFixed(2).replace('.',','));}
  },[filters]);
  useEffect(()=>{void load();},[load]);
  async function signIn(event:React.FormEvent){event.preventDefault();setError('');const response=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const result=await response.json() as {error?:string};if(!response.ok){setError(result.error||'Credenciais inválidas.');return;}setLogin(false);void load();}
  async function action(orderNumber:string,actionName:string){setBusy(orderNumber+actionName);const response=await fetch('/api/admin/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderNumber,action:actionName})});const result=await response.json() as {error?:string};if(!response.ok)alert(result.error);setBusy('');void load();}
  async function reviewAction(id:number,actionName:string){setBusy(`review${id}`);const response=await fetch('/api/admin/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action:actionName})});const result=await response.json() as {error?:string};if(!response.ok)alert(result.error);setBusy('');void load();}
  async function updateSpend(){const valueCents=Math.round(Number(dailySpend.replace(',','.'))*100),completeCents=Math.round(Number(completePrice.replace(',','.'))*100),upsellCents=Math.round(Number(upsellPrice.replace(',','.'))*100);const response=await fetch('/api/admin/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'update_settings',valueCents,completeCents,upsellCents})});if(response.ok)void load();}
  async function uploadBook(event:React.ChangeEvent<HTMLInputElement>,slug:string){const file=event.target.files?.[0];if(!file)return;if(file.type!=='application/pdf'){setBookStatus('Selecione um PDF.');return;}setBookStatus('Enviando livro...');const response=await fetch(`/api/admin/ebook?book=${encodeURIComponent(slug)}`,{method:'PUT',headers:{'Content-Type':'application/pdf'},body:file});const result=await response.json() as {error?:string};setBookStatus(response.ok?'Livro atualizado.':result.error||'Falha no envio.');event.target.value='';}
  const readingUrl=(token:string)=>`${window.location.origin}/leitura/${token}`;
  async function copyAd(variant:typeof adVariants[number]){const url=`${window.location.origin}/?landing_variant=${variant.id==='leitura-ebook'?'B':'A'}&utm_source=meta&utm_medium=paid_social&utm_campaign=tarot_lancamento&utm_content=${variant.id}`;await navigator.clipboard.writeText(`${variant.primary}\n\n${variant.headline}\n\n${url}`);alert('Anúncio e link rastreável copiados.');}
  if(login)return <main className="admin-login"><form onSubmit={signIn}><span className="brand-mark">✦</span><p className="eyebrow">Chama Sofia</p><h1>Acesso à gestão</h1><label>E-mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary-button">ENTRAR</button></form></main>;
  if(!data)return <main className="admin-login">Carregando...</main>;
  const d=data.dashboard,f=d.funnel;
  const funnel=[['Landing',f.visitors],['CTA',f.cta],['Pergunta',f.questions],['Oferta',f.offers],['Pix',f.pix],['Pagamento',f.paid]] as const;
  const rate=(from:number,to:number)=>from?`${(to/from*100).toFixed(1)}%`:'—';
  return <main className="admin-shell"><header><div><p className="eyebrow">Cockpit comercial</p><h1>Tarot Chama Sofia</h1></div><div className="admin-actions"><button className="admin-test-button" onClick={()=>window.open('/?test=1','_blank','noopener,noreferrer')}>Abrir jornada de teste</button><a className="admin-download" href="/assets/social/anuncio-tarot-livro-v2.png" download>Baixar anúncio</a>{[['tarot-para-iniciantes','Tarot'],['pomba-gira','Pomba Gira'],['preto-velho','Preto Velho']].map(([slug,label])=><label className="admin-upload" key={slug}>Enviar {label}<input type="file" accept="application/pdf" onChange={event=>void uploadBook(event,slug)}/></label>)}<button onClick={()=>void load()}>Atualizar</button>{bookStatus&&<small>{bookStatus}</small>}</div></header>
    <section className="admin-filters"><label>Período<select value={filters.period} onChange={e=>setFilters({...filters,period:e.target.value})}><option value="today">Hoje</option><option value="yesterday">Ontem</option><option value="7d">7 dias</option><option value="30d">30 dias</option><option value="all">Todo período</option></select></label>{([['source','Origem',data.filters.options.sources],['campaign','Campanha',data.filters.options.campaigns],['creative','Criativo',data.filters.options.creatives],['device','Dispositivo',data.filters.options.devices],['variant','Variante',data.filters.options.variants],['offer','Oferta',data.filters.options.offers]] as const).map(([key,label,options])=><label key={key}>{label}<select value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}><option value="all">Todos</option>{options.map(value=><option value={value} key={value}>{value}</option>)}</select></label>)}<button onClick={()=>setFilters(initialFilters)}>Limpar</button></section>
    <section className="mode-summary"><article><span>PRODUÇÃO</span><strong>{d.totalSales} venda(s) · {money(d.revenue)}</strong><small>somente clientes reais</small></article><article className="test"><span>TESTES</span><strong>{d.test.sales} venda(s) · {money(d.test.revenue)}</strong><small>{d.test.total} pedido(s), completamente separados</small></article></section>
    <section className="metrics">{[['Visitantes',d.visitors],['Sessões',d.sessions],['Vendas',d.totalSales],['Faturamento',money(d.revenue)],['Receita Essencial',money(d.essentialRevenue)],['Receita Completa',money(d.completeRevenue)],['Receita Upsell',money(d.upsellRevenue)],['Ticket médio',money(d.averageTicket)],['Conversão',`${(d.conversion*100).toFixed(1)}%`],['Adesão ao pacote',`${(d.completeAdoption*100).toFixed(1)}%`],['Taxa de upsell',`${(d.upsellRate*100).toFixed(1)}%`],['Preço atual',d.pricing.formatted],['Restam na faixa',d.pricing.remaining??'∞']].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section>
    <section className={`guardian guardian-${d.guardian.level}`}><div><span>STATUS DA OPERAÇÃO</span><strong>{d.guardian.label}</strong><p>{d.guardian.message}</p></div><div className="economics"><label>Gasto diário<input value={dailySpend} onChange={e=>setDailySpend(e.target.value)} inputMode="decimal"/></label><label>Pacote completo<input value={completePrice} onChange={e=>setCompletePrice(e.target.value)} inputMode="decimal"/></label><label>Upsell biblioteca<input value={upsellPrice} onChange={e=>setUpsellPrice(e.target.value)} inputMode="decimal"/><button onClick={()=>void updateSpend()}>Salvar configurações</button></label><p>Investimento estimado: <b>{money(d.economics.estimatedSpend)}</b></p><p>CAC: <b>{d.economics.cac===null?'AMOSTRA INSUFICIENTE':money(d.economics.cac)}</b></p><p>ROAS: <b>{d.economics.roas===null?'AMOSTRA INSUFICIENTE':`${d.economics.roas.toFixed(2)}x`}</b></p><p>Receita/visitante: <b>{money(d.economics.revenuePerVisitor)}</b></p></div></section>
    <section className="funnel-panel">{funnel.map(([label,value],index)=><div key={label}><span>{label}</span><strong>{value}</strong>{index>0&&<small className="funnel-rate">{rate(funnel[index-1][1],value)}</small>}</div>)}</section>
    <section className="behavior-panel"><div className="panel-title"><h2>Comportamento e abandono</h2><span>sessões estimadas por transição</span></div><div className="behavior-grid">{[['Antes do CTA',d.abandonment.beforeCta],['Após o CTA',d.abandonment.afterCta],['Após a pergunta',d.abandonment.afterQuestion],['Após a oferta',d.abandonment.afterOffer],['Após gerar Pix',d.abandonment.afterPix],['Scroll 25%',d.behavior.depth25],['Scroll 50%',d.behavior.depth50],['Scroll 75%',d.behavior.depth75],['Scroll 90%',d.behavior.depth90],['FAQ',d.behavior.faqOpened],['Suporte',d.behavior.contactClicks]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{d.pricePerformance.length>0&&<div className="price-performance"><h3>Conversão por preço registrado</h3>{d.pricePerformance.map(row=><p key={row.price}><b>{money(row.price)}</b> · {row.sales}/{row.checkouts} compras · {(row.conversion*100).toFixed(1)}%</p>)}</div>}</section>
    <section className="growth-panel">{[['Formulários recuperáveis',d.recovery.openForms],['1º lembrete',d.recovery.formFirst+d.recovery.pixFirst],['2º lembrete',d.recovery.second],['Retomadas',d.recovery.resumed],['Indicações',d.growth.referrals],['Interesse em upsell',d.growth.upsellClicks]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section>
    {reviews.length>0&&<section className="admin-reviews"><div className="panel-title"><h2>Avaliações reais</h2><span>{reviews.length} recebida(s)</span></div>{reviews.map(review=><article key={review.id}><div><span>{'★'.repeat(review.rating)}</span><strong>{review.display_name} · {review.order_number}</strong><p>{review.comment||'Sem comentário'}</p><small>Consentimento público: {review.public_consent?'sim':'não'} · {review.is_test?'TESTE':review.moderation_status}</small></div><div className="row-actions"><button disabled={busy!==''||!review.public_consent} onClick={()=>void reviewAction(review.id,'approve')}>Aprovar</button><button disabled={busy!==''} onClick={()=>void reviewAction(review.id,'hide')}>Ocultar</button><button disabled={busy!==''||!review.public_consent} onClick={()=>void reviewAction(review.id,'feature')}>{review.featured?'Remover destaque':'Destacar'}</button><button disabled={busy!==''} onClick={()=>void reviewAction(review.id,'delete')}>Excluir</button></div></article>)}</section>}
    <section className="ad-tests-panel"><div className="panel-title"><div><p className="eyebrow">Criativos rastreáveis</p><h2>Um teste por vez</h2></div><span>A e B usam landing_variant persistente</span></div><div className="ad-tests-grid">{adVariants.map(variant=><article key={variant.id}><span>{variant.label}</span><h3>{variant.headline}</h3><p>{variant.primary}</p><button onClick={()=>void copyAd(variant)}>Copiar anúncio + link</button></article>)}</div></section>
    <section className="orders-panel"><div className="panel-title"><h2>Pedidos recentes</h2><span>{data.orders.length} exibidos</span></div><div className="table-wrap"><table><thead><tr><th>Pedido</th><th>Cliente / pergunta</th><th>Atribuição</th><th>Oferta</th><th>Status</th><th>Ações</th></tr></thead><tbody>{data.orders.map(order=><tr key={order.id}><td><strong>{order.order_number}</strong><small>{new Date(order.created_at).toLocaleString('pt-BR')}</small>{Boolean(order.is_test)&&<small className="test-chip">TESTE</small>}</td><td><strong>{order.customer_name}</strong><small>{order.customer_email||order.customer_whatsapp}</small><p><b>{order.category}:</b> {order.question}</p></td><td>{order.utm_source||'direto'}<small>{order.utm_campaign||'sem campanha'} · {order.utm_content||'sem criativo'}</small><small>{order.device_type||'unknown'} · variante {order.landing_variant||'A'}</small></td><td>{order.offer_code||'essential'}<small>{money(order.price)}</small><small>upsell: {order.upsell_status||'—'}</small></td><td><span className={`status status-${order.payment_status}`}>{order.payment_status}</span><small>{order.reading_status}</small>{order.recovery_first_sent_at&&<small>1º lembrete enviado</small>}{order.recovery_second_sent_at&&<small>2º lembrete enviado</small>}{order.recovery_error&&<small className="status-error">Falha na recuperação</small>}</td><td><div className="row-actions">{['reading_generated','delivered'].includes(order.reading_status)&&<><button onClick={()=>window.open(readingUrl(order.public_token),'_blank','noopener,noreferrer')}>Abrir leitura</button><button onClick={()=>void navigator.clipboard.writeText(readingUrl(order.public_token))}>Copiar link</button><button disabled={busy!==''} onClick={()=>void action(order.order_number,'resend')}>Reenviar</button></>}{order.payment_status==='pending'&&<button disabled={busy!==''} onClick={()=>void action(order.order_number,'mark_paid')}>Confirmar Pix</button>}<button disabled={busy!==''} onClick={()=>void action(order.order_number,order.is_test?'mark_real':'mark_test')}>{order.is_test?'Incluir como real':'Marcar como teste'}</button></div></td></tr>)}</tbody></table></div></section>
  </main>;
}
